name: controlegastos
description: Um aplicativo para controle de gastos de viagem com funcionalidades offline.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Para salvar preferências simples do usuário (moeda, limite de gastos)
  shared_preferences: ^2.2.3

  # Para o banco de dados local (armazenar despesas)
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0

  # Utilitário para formatação de data e moeda
  intl: ^0.19.0

  cupertino_icons: ^1.0.2
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
